
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 3.05
//   File : Evt_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace BondEtwSample
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "3.05")]
    public partial class Evt
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Time { get; set; }

        [global::Bond.Id(2)]
        public string Message { get; set; }

        public Evt()
            : this("BondEtwSample", "Evt")
        {}

        protected Evt(string fullName, string name)
        {
            Time = string.Empty;
            Message = string.Empty;
        }
    }
} // Microsoft.Manageability.Monitoring.Communication.Common.Bond
